name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/eli/projects/eli-robinson.dev
    steps:
      - name: Pull latest code
        run: git pull

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Restart service
        run: sudo systemctl restart personal-website.service
